MVC  with CRUD/Models/ErrorViewModel.cs
using System;

namespace MVC__with_CRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC  with CRUD/Controllers/DoctorsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using DataAccesse_Layer;
namespace MVC__with_CRUD.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly IDoctorsRepository Result;
        private readonly ILocationRepository Add;
        private readonly string Connection;
        public DoctorsController(IDoctorsRepository injectbject, IConfiguration service)
        {
            Result = injectbject;
            Add = new LocationRepository(service);
            Connection = service.GetConnectionString("Dbconnection");
        }
        // GET: DoctorsController
        public ActionResult Index()
        {
            try
            {
                var Obj = Result.GetAll();
                return View("View", Obj);
            }
            catch
            {
                return View();
            }
        }

        // GET: DoctorsController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var obj = Result.GetbyID(id);
                obj.Locations = Add.GetLocation().ToList();
                return View("Details", obj);
            }
            catch
            {
                return View();
            }
        }

        // GET: DoctorsController/Create
        public ActionResult add()
        {
            try
            {
                var Creat = new Doctors();
                Creat.Locations = Add.GetLocation().ToList();
                return View("Create",Creat);
            }
            catch
            {
                return View();
            }
        }

        // POST: DoctorsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Doctors add)
        
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Result.Insert(add);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View("Create", add);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: DoctorsController/Edit/5
        public ActionResult Edit(long id)
        {
            try
            {
                var obj = Result.GetbyID(id);
                obj.Locations = Add.GetLocation().ToList();
                return View("Update", obj);
            }
            catch
            {
                return View();
            }
        }

        // POST: DoctorsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long id, Doctors replace)
        {
            try
            {
                Result.Update(id, replace);   
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("View");
            }
        }

        // GET: DoctorsController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var Get = Result.GetbyID(id);
                return View("Delete", Get);
            }
            catch 
            {
                return View();
            }
        }

        // POST: DoctorsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete1(int DoctorsID)
        {
            try
            {
                Result.Delete(DoctorsID);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("error");
            }
        }
        public ActionResult LogIN()
        {
            return View("Login", new Doctors());
        }

    }
}

MVC  with CRUD/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC__with_CRUD.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVC__with_CRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC  with CRUD/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccesse_Layer;
using Microsoft.Extensions.Configuration;


namespace MVC__with_CRUD.Controllers
{
    
    public class LoginController : Controller
    {
       
       
        public IActionResult Index()
        {
            try
            {

                return View("View");
               
               
            }
            catch
            {
                return View();
            }
        }
        public IActionResult Index(Login ad)
        {
            try
            {

                return View("View", new Login());


            }
            catch
            {
                return View();
            }
        }

        public IActionResult Details(Login ad)
        {
            try
            {
                if (ad.Password == "Siva")
                {

                    return View();
                }
                return View();
               
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC  with CRUD/Views/Doctors/Create.cshtml
@model DataAccesse_Layer.Doctors

@{
    ViewData["Title"] = "Create";
}

<h1 class="pl-5">Create</h1>

<h4 class="pl-5">Doctors</h4>
<hr />
<div class="row p-5">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DoctorsName" class="control-label"></label>
                <input asp-for="DoctorsName" class="form-control" />
                <span asp-validation-for="DoctorsName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PassoutYear" class="control-label"></label>
                <input asp-for="PassoutYear" type="tel" class="form-control" />
                <span asp-validation-for="PassoutYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qualification" class="control-label"></label>
                <input asp-for="Qualification" class="form-control" />
                <span asp-validation-for="Qualification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" type="tel" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Addresss" class="control-label"></label>
                <input asp-for="Addresss" class="form-control" />
                <span asp-validation-for="Addresss" class="text-danger"></span>
            </div>
            <div class="form-group" >
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class="form-control" asp-items="@(new SelectList(Model.Locations,"LocationId","LocationName"))">
                    <option value="0">--Select--</option>

                </select>
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC  with CRUD/Views/Doctors/Delete.cshtml
@model DataAccesse_Layer.Doctors

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctors</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorsName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DoctorsName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorsID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DoctorsID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PassoutYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PassoutYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Qualification)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Addresss)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Addresss)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LocationId)
        </dd>
    </dl>
    
    <form asp-action="Delete1">
        <input asp-for="DoctorsID" type="hidden" class="form-control" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC  with CRUD/Views/Doctors/Details.cshtml
@model DataAccesse_Layer.Doctors

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Doctors</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorsName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DoctorsName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DoctorsID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DoctorsID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PassoutYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PassoutYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Qualification)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Addresss)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Addresss)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LocationId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.DoctorsID }) |
    <a asp-action="Index">Back to List</a>
</div>

MVC  with CRUD/Views/Doctors/Update.cshtml
@model DataAccesse_Layer.Doctors

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Doctors</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DoctorsName" class="control-label"></label>
                <input asp-for="DoctorsName" class="form-control" />
                <span asp-validation-for="DoctorsName" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none">
                <label asp-for="DoctorsID" class="control-label"></label>
                <input asp-for="DoctorsID" type="hidden" class="form-control" />
                <span asp-validation-for="DoctorsID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassoutYear" class="control-label"></label>
                <input asp-for="PassoutYear" type="tel" class="form-control" />
                <span asp-validation-for="PassoutYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qualification" class="control-label"></label>
                <input asp-for="Qualification" class="form-control" />
                <span asp-validation-for="Qualification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" type="tel" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Addresss" class="control-label"></label>
                <input asp-for="Addresss" class="form-control" />
                <span asp-validation-for="Addresss" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <select asp-for="LocationId" class="form-control" asp-items="@(new SelectList(Model.Locations,"LocationId","LocationName"))">
                    <option value="0">--Select--</option>

                </select>
                <span asp-validation-for="Locations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC  with CRUD/Views/Doctors/View.cshtml
@model IEnumerable<DataAccesse_Layer.Doctors>

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<p>
    <a asp-controller="Doctors" asp-action="add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DoctorsName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorsID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassoutYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qualification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addresss)
            </th>
            <th>@Html.DisplayNameFor(model => model.LocationId)</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorsName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorsID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PassoutYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qualification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Addresss)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.DoctorsID }) |
                @Html.ActionLink("Details", "Details", new { id = item.DoctorsID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.DoctorsID })
            </td>
        </tr>
}
    </tbody>
</table>

MVC  with CRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>To My Page</p>
    <form class="form-group" asp-action="Create">
        <div class="align-content-center">
            <input type="button" value="Create New" class="btn-primary" />
        </div>
    </form>
</div>
 

MVC  with CRUD/Views/Login/View.cshtml
@model DataAccesse_Layer.Login

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>

<h4>Login</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email"type="email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

MVC  with CRUD/Views/Login/View1.cshtml
@model DataAccesse_Layer.Login

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>

<h4>Login</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email"type="email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

MVC  with CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC__with_CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-Primary border-bottom box-shadow mb-3">
            <div class="container" id="constt">
                               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="Index">Create</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC__with_CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>